package resample

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/go-gfx/gfx/raster"
)

// loadBin reads a raw row-major RGBA fixture (see testdata/generate.py) into a
// raster.Image of the given size.
func loadBin(t *testing.T, name string, w, h int) *raster.Image {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	if len(b) != w*h*4 {
		t.Fatalf("%s: have %d bytes, want %d for %dx%d RGBA", name, len(b), w*h*4, w, h)
	}
	im := raster.New(w, h)
	copy(im.Pix, b)
	return im
}

// psnrPremultiplied is the peak signal-to-noise ratio in dB between two
// equal-length RGBA byte slices, measured in PREMULTIPLIED space: each colour
// channel is weighted by its own alpha before differencing, and alpha is
// compared directly. This is the visually meaningful metric for images with
// transparency — the RGB of a near-transparent pixel, which no display shows,
// cannot dominate the error the way a straight per-byte comparison lets it.
// On a fully opaque image it is exactly the straight RGBA PSNR. +Inf when the
// two are identical.
func psnrPremultiplied(a, b []uint8) float64 {
	var se float64
	n := 0
	for i := 0; i < len(a); i += 4 {
		aa, ba := float64(a[i+3]), float64(b[i+3])
		for c := 0; c < 3; c++ {
			d := float64(a[i+c])*aa/255 - float64(b[i+c])*ba/255
			se += d * d
			n++
		}
		d := aa - ba
		se += d * d
		n++
	}
	if se == 0 {
		return math.Inf(1)
	}
	return 10 * math.Log10(255*255/(se/float64(n)))
}

var parityModes = map[string]Mode{"bicubic": Bicubic, "lanczos": Lanczos}

// TestResampleMatchesPillow checks every case in testdata/manifest.json against
// its Pillow reference (Pillow 12; the reference is regenerated by generate.py).
// Pillow's RGBA resize is premultiplied-alpha aware, so:
//   - opaque fixtures are compared against Resize (straight == premultiplied when
//     alpha is 255), and
//   - the transparent disk is compared against ResizePremultiplied.
//
// Parity is measured as premultiplied-space PSNR, with a documented minimum per
// family (logged for every case). We stay in float64 end-to-end while Pillow's
// uint8 path clips an 8-bit intermediate between the two passes and keeps a
// faint sub-LSB alpha halo where we round to zero, which sets the ceiling; the
// numbers are recorded in docs/perf.md.
func TestResampleMatchesPillow(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Input  string `json:"input"`
		W      int    `json:"w"`
		H      int    `json:"h"`
		Mode   string `json:"mode"`
		Premul bool   `json:"premul"`
		DW     int    `json:"dw"`
		DH     int    `json:"dh"`
		Ref    string `json:"ref"`
	}
	if err := json.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) == 0 {
		t.Fatal("empty manifest")
	}
	// Observed lows across the fixtures: opaque >= 52.9 dB, premultiplied >= 42.7
	// dB. The bars sit below those with margin for a platform's float rounding.
	const straightMin, premulMin = 45.0, 40.0
	for _, c := range cases {
		t.Run(c.Ref, func(t *testing.T) {
			src := loadBin(t, c.Input, c.W, c.H)
			var got *raster.Image
			var err error
			if c.Premul {
				got, err = ResizePremultiplied(src, c.DW, c.DH, parityModes[c.Mode])
			} else {
				got, err = Resize(src, c.DW, c.DH, parityModes[c.Mode])
			}
			if err != nil {
				t.Fatal(err)
			}
			want := loadBin(t, c.Ref, c.DW, c.DH)
			p := psnrPremultiplied(got.Pix, want.Pix)
			min := straightMin
			if c.Premul {
				min = premulMin
			}
			t.Logf("PSNR vs Pillow = %.2f dB (min %.0f)", p, min)
			if p < min {
				t.Errorf("PSNR %.2f dB below the %.0f dB parity bar", p, min)
			}
		})
	}
}
