package resample

// s390x: z/Architecture vector-facility float64 multiply-accumulate (axpy)
// kernel generated by go-asmgen (simd_s390x.s). The vector facility is part of
// the s390x baseline the Go toolchain targets, so the kernel is always callable.
// s390x is big-endian, but axpy is elementwise (no cross-lane interleave), so
// lane order is irrelevant.
//
//go:generate sh -c "cd asmgen/s390x && GOWORK=off GOFLAGS=-mod=mod go run gen.go && mv simd_s390x.s ../../simd_s390x.s"

// HaveSIMD reports that this build ships the SIMD axpy kernel.
const HaveSIMD = true

// SIMDName identifies the vector kernel family for the per-arch test log.
const SIMDName = "z/vector"

// axpy computes dst[i] += a*src[i] over the whole pair of slices (same non-zero
// length) via the vector kernel; bit-identical to the scalar oracle (s390x fuses
// the scalar form to FMADD, which VFMADB reproduces).
func axpy(dst, src []float64, a float64) {
	if len(dst) == 0 {
		return
	}
	axpyVX(&dst[0], &src[0], a, len(dst))
}

//go:noescape
func axpyVX(dst, src *float64, a float64, n int)
