package resample

// amd64: SSE2 float64 multiply-accumulate (axpy) kernel generated by go-asmgen
// (simd_amd64.s). SSE2 is part of the amd64 baseline (GOAMD64=v1), so the kernel
// is always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/amd64 && GOWORK=off GOFLAGS=-mod=mod go run gen.go && mv simd_amd64.s ../../simd_amd64.s"

// HaveSIMD reports that this build ships the SIMD axpy kernel, so the filtered
// vertical pass is routed through it. The per-arch CI job validates it against
// the scalar oracle.
const HaveSIMD = true

// SIMDName identifies the vector kernel family for the per-arch test log.
const SIMDName = "SSE2"

// axpy computes dst[i] += a*src[i] over the whole pair of slices, which must be
// the same non-zero length, via the SSE2 kernel.
func axpy(dst, src []float64, a float64) {
	if len(dst) == 0 {
		return
	}
	axpySSE2(&dst[0], &src[0], a, len(dst))
}

//go:noescape
func axpySSE2(dst, src *float64, a float64, n int)
