// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·axpySSE2(SB), NOSPLIT, $0-32
	MOVQ dst+0(FP), AX
	MOVQ src+8(FP), BX
	MOVSD a+16(FP), X0
	MOVQ n+24(FP), CX
	MOVDDUP X0, X0
	block:
	CMPQ CX, $4
	JL tail
	MOVUPD (BX), X1
	MOVUPD 16(BX), X2
	MULPD X0, X1
	MULPD X0, X2
	MOVUPD (AX), X3
	MOVUPD 16(AX), X4
	ADDPD X1, X3
	ADDPD X2, X4
	MOVUPD X3, (AX)
	MOVUPD X4, 16(AX)
	ADDQ $32, AX
	ADDQ $32, BX
	SUBQ $4, CX
	JMP block
	tail:
	TESTQ CX, CX
	JZ done
	MOVSD (BX), X1
	MULSD X0, X1
	MOVSD (AX), X2
	ADDSD X1, X2
	MOVSD X2, (AX)
	ADDQ $8, AX
	ADDQ $8, BX
	DECQ CX
	JMP tail
	done:
	RET

