package resample

// arm64: NEON float64 multiply-accumulate (axpy) kernel generated by go-asmgen
// (simd_arm64.s). NEON (ASIMD) is part of the arm64 baseline the Go toolchain
// requires, so the kernel is always callable — there is no CPU-feature branch.
//
//go:generate sh -c "cd asmgen/arm64 && GOWORK=off GOFLAGS=-mod=mod go run gen.go && mv simd_arm64.s ../../simd_arm64.s"

// HaveSIMD reports that this build ships the SIMD axpy kernel.
const HaveSIMD = true

// SIMDName identifies the vector kernel family for the per-arch test log.
const SIMDName = "NEON"

// axpy computes dst[i] += a*src[i] over the whole pair of slices (same non-zero
// length) via the NEON kernel; bit-identical to the scalar oracle (arm64 fuses
// the scalar form to FMADDD, which VFMLA reproduces).
func axpy(dst, src []float64, a float64) {
	if len(dst) == 0 {
		return
	}
	axpyNEON(&dst[0], &src[0], a, len(dst))
}

//go:noescape
func axpyNEON(dst, src *float64, a float64, n int)
